### ISSUE TITLE
Use slim version of hub image to minimise exposure to vulnerabilities

### ISSUE THREAD

**Issue by vvcb** [lsc-sde/iac-flux-jupyter#10]
z2jh's security documentation recommends using the slim version of the image for the hub pod. https://z2jh.jupyter.org/en/latest/administrator/security.html#minimal-hub-image

> The default hub image includes some useful debugging tools. You can use the slim version of image to minimise your exposure to vulnerabilities in those optional tools.

```yaml
hub:
  image:
    # The slim variant excludes a few non-essential packages that are useful
    # when debugging something from the hub pod. To use it, apply this
    # configuration.
    #
    name: quay.io/jupyterhub/k8s-hub-slim
```
