### ISSUE TITLE
Jupyterhub admin (VC) is no longer able to access the admin page on hub

### ISSUE THREAD

**Issue by vvcb** [lsc-sde/iac-flux-jupyter#36]
I have not been able to access the admin page on JupyterHub for sometime now. 

This is likely the result of https://github.com/lsc-sde/iac-flux-jupyter/blob/main/jupyterhub/config/hub.yaml#L28-L29

Previously there was an `admin_users` key which has been replaced with `admin_groups`.

Am I assigned to this group and if so where is this done? In Entra?

Options:
1. Check that @vvcb  is added to the `jupyterhub_admins_role` group and this works
2. Recreate `admin_users` section and assign @vvcb  to it.

**Comment by qcaas-nhs-sjt** [comment]
Yes, this is handled by entra id groups, I'll look into this

**Comment by qcaas-nhs-sjt** [comment]
Okay so i got the config yaml from below
```
> kubectl get configmap/hub-config -n jupyterhub -o=jsonpath="{.data.values\.yaml}"
prePuller:
  hook:
    enabled: true
hub:
  image:
    pullPolicy: Always
    name: lscsde/jupyterhub
    tag: 0.1.14
  config:
    AzureAdOAuthenticator:
      client_id: 8af6c62f-5713-4882-a8b1-67d5ee3b313f
      oauth_callback_url: "https://jupyter.xlscsde.nhs.uk/hub/oauth_callback"
      tenant_id: f12f0279-8a84-4068-8322-7a6fb0f839b8
      scope:
        - openid
        - name
        - profile
        - email
        - groups
        - roles
      username_claim: unique_name
      manage_groups: true
      allow_all: true
      allowed_groups:
      - "affc391f-2cbd-44af-9c0b-06445ff6f721"
      - "4c2c7816-2b9d-4118-829c-939582add676"
      user_groups_claim: groups
      admin_groups:
      - "4c2c7816-2b9d-4118-829c-939582add676"
      allowed_users:
      - vishnu.chandrabalan@lthtr.nhs.uk
      - shaun.turner1@nhs.net
      enable_auth_state: true
    JupyterHub:
      authenticator_class: azuread
      admin_access: true
      template_paths:
        - "/usr/local/etc/jupyterhub/custom_templates"
      template_vars:
        announcement: |
          Preview only.
          Subject to rapid, breaking changes.
          Contact Vishnu.Chandrabalan@lthtr.nhs.uk with feedback/comments.
  # extraFiles:
    # https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html#hub-extrafiles
    # customSpawnPageTemplate:
    #   mountPath: /usr/local/etc/jupyterhub/custom_templates/spawn.html

    #customLogo:
    #  mountPath: /usr/local/share/jupyterhub/static/lander-logo.png
    # customPageTemplate:
    #   mountPath: /usr/local/etc/jupyterhub/custom_templates/page.html

    #customConfig:
    #  mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/jupyterhub_config_custom.py

  # https://discourse.jupyter.org/t/trouble-configuring-ingress-for-helm-chart/5050/3
  #baseUrl: /landerhub
  extraEnv:
  - name: WORKSPACE_MANAGER
    value: lscsde
  livenessProbe:
    initialDelaySeconds: 5
PS C:\Users\shaun.turner\Documents\Sources\NHS\lsc-sde\iac\terraform\azure\azure\03-core-infrastructure> kubectl get configmap/hub-config -n jupyterhub -o=jsonpath="{.data.values\.yaml}"
prePuller:
  hook:
    enabled: true
hub:
  image:
    pullPolicy: Always
    name: lscsde/jupyterhub
    tag: 0.1.14
  config:
    AzureAdOAuthenticator:
      client_id: 8af6c62f-5713-4882-a8b1-67d5ee3b313f
      oauth_callback_url: "https://jupyter.xlscsde.nhs.uk/hub/oauth_callback"
      tenant_id: f12f0279-8a84-4068-8322-7a6fb0f839b8
      scope:
        - openid
        - name
        - profile
        - email
        - groups
        - roles
      username_claim: unique_name
      manage_groups: true
      allow_all: true
      allowed_groups:
      - "affc391f-2cbd-44af-9c0b-06445ff6f721"
      - "4c2c7816-2b9d-4118-829c-939582add676"
      user_groups_claim: groups
      admin_groups:
      - "4c2c7816-2b9d-4118-829c-939582add676"
      allowed_users:
      - vishnu.chandrabalan@lthtr.nhs.uk
      - shaun.turner1@nhs.net
      enable_auth_state: true
    JupyterHub:
      authenticator_class: azuread
      admin_access: true
      template_paths:
        - "/usr/local/etc/jupyterhub/custom_templates"
      template_vars:
        announcement: |
          Preview only.
          Subject to rapid, breaking changes.
          Contact Vishnu.Chandrabalan@lthtr.nhs.uk with feedback/comments.
  # extraFiles:
    # https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html#hub-extrafiles
    # customSpawnPageTemplate:
    #   mountPath: /usr/local/etc/jupyterhub/custom_templates/spawn.html

    #customLogo:
    #  mountPath: /usr/local/share/jupyterhub/static/lander-logo.png
    # customPageTemplate:
    #   mountPath: /usr/local/etc/jupyterhub/custom_templates/page.html

    #customConfig:
    #  mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/jupyterhub_config_custom.py

  # https://discourse.jupyter.org/t/trouble-configuring-ingress-for-helm-chart/5050/3
  #baseUrl: /landerhub
  extraEnv:
  - name: WORKSPACE_MANAGER
    value: lscsde
  livenessProbe:
    initialDelaySeconds: 5
```

You can see that the admin_groups is set to **4c2c7816-2b9d-4118-829c-939582add676**

If I query this in Azure Entra ID:
```
C:\Users\ShaunTurner.AzureAD>az ad group show -g 4c2c7816-2b9d-4118-829c-939582add676
{
  "deletionTimestamp": null,
  "description": null,
  "dirSyncEnabled": null,
  "displayName": "JupyterhubAdminsProd",
  "lastDirSyncTime": null,
  "mail": null,
  "mailEnabled": false,
  "mailNickname": "800b5137-d",
  "objectId": "4c2c7816-2b9d-4118-829c-939582add676",
  "objectType": "Group",
  "odata.metadata": "https://graph.windows.net/f12f0279-8a84-4068-8322-7a6fb0f839b8/$metadata#directoryObjects/@Element",
  "odata.type": "Microsoft.DirectoryServices.Group",
  "onPremisesDomainName": null,
  "onPremisesNetBiosName": null,
  "onPremisesSamAccountName": null,
  "onPremisesSecurityIdentifier": null,
  "provisioningErrors": [],
  "proxyAddresses": [],
  "securityEnabled": true
}
```

You can then query the member list:
```
C:\Users\ShaunTurner.AzureAD>az ad group member list -g 4c2c7816-2b9d-4118-829c-939582add676
```
or you can look it up on the azure portal:

![image](https://github.com/lsc-sde/iac-flux-jupyter/assets/77382942/6f038ad1-54ce-4e34-80b9-663b873b59d7)

![image](https://github.com/lsc-sde/iac-flux-jupyter/assets/77382942/45142de0-ae9a-4273-a1b8-14ed47755126)

As you can see you are showing up in that list

My guess is that either:
* The claim for groups is not coming down properly
* There is an issue with the custom docker image which is causing this to no longer work.

Will investigate further

**Comment by qcaas-nhs-sjt** [comment]
issue seems to exist in other environments as well as I've got the same issue on all three environments

I've added vishnu specifically to the admin config and have cherry-picked this into the main branch also.

```
prePuller:
  hook:
    enabled: true
hub:
  image:
    pullPolicy: Always
    name: lscsde/jupyterhub
    tag: 0.1.14
  config:
    AzureAdOAuthenticator:
      client_id: 8af6c62f-5713-4882-a8b1-67d5ee3b313f
      oauth_callback_url: "https://jupyter.xlscsde.nhs.uk/hub/oauth_callback"
      tenant_id: f12f0279-8a84-4068-8322-7a6fb0f839b8
      scope:
        - openid
        - name
        - profile
        - email
        - groups
        - roles
      username_claim: unique_name
      manage_groups: true
      allow_all: true
      allowed_groups:
      - "affc391f-2cbd-44af-9c0b-06445ff6f721"
      - "4c2c7816-2b9d-4118-829c-939582add676"
      user_groups_claim: groups
      admin_groups:
      - "4c2c7816-2b9d-4118-829c-939582add676"
      allowed_users:
      - vishnu.chandrabalan@lthtr.nhs.uk
      - shaun.turner1@nhs.net
      admin_users:
      - vishnu.chandrabalan@lthtr.nhs.uk
      enable_auth_state: true
    JupyterHub:
      authenticator_class: azuread
      admin_access: true
      template_paths:
        - "/usr/local/etc/jupyterhub/custom_templates"
      template_vars:
        announcement: |
          Preview only.
          Subject to rapid, breaking changes.
          Contact Vishnu.Chandrabalan@lthtr.nhs.uk with feedback/comments.
  # extraFiles:
    # https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html#hub-extrafiles
    # customSpawnPageTemplate:
    #   mountPath: /usr/local/etc/jupyterhub/custom_templates/spawn.html

    #customLogo:
    #  mountPath: /usr/local/share/jupyterhub/static/lander-logo.png
    # customPageTemplate:
    #   mountPath: /usr/local/etc/jupyterhub/custom_templates/page.html

    #customConfig:
    #  mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/jupyterhub_config_custom.py

  # https://discourse.jupyter.org/t/trouble-configuring-ingress-for-helm-chart/5050/3
  #baseUrl: /landerhub
  extraEnv:
  - name: WORKSPACE_MANAGER
    value: lscsde
  livenessProbe:
    initialDelaySeconds: 5
```
